set lines=30
syntax on
set showcmd
set laststatus=2
set nocompatible
set number
set tabstop=4 
inoremap jk <ESC>

filetype off

set rtp+=~/.vim/bundle/vundle/

call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'vim-scripts/tComment'
Bundle 'scrooloose/nerdtree'
Bundle 'plasticboy/vim-markdown'
Bundle 'Lokaltog/vim-powerline'
Bundle 'vim-latex/vim-latex'

filetype plugin indent on
filetype on

nmap <F2> :NERDTreeToggle<cr>
